# -*- coding: utf-8 -*-
"""calories.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYZ-wTob_-VwCMIgy9RYx81yMxkFJFxT

importing the dependencies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

"""data collection & pro"""

calories = pd.read_csv('/content/calories.csv')
calories.head()

exercise_data = pd.read_csv('/content/exercise.csv')
exercise_data.head()

"""Combining the two Dataframes"""

calories = pd.concat([exercise_data,calories['Calories']], axis=1)

calories.head()

calories.shape

calories.info()

calories.isnull().sum()

"""Data Visualization"""

sns.set()

sns.countplot(calories['Gender'])

# finding the distribution of "Age" column
sns.distplot(calories['Age'])

# finding the distribution of "Height" column
sns.distplot(calories['Height'])

# finding the distribution of "Weight" column
sns.distplot(calories['Weight'])

"""finding the correlation in the dataset"""

correlation = calories.corr()

plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot=True, annot_kws={'size':8}, cmap='Blues')

calories.replace({"Gender":{'male':0,'female':1}}, inplace=True)

calories.head()

X = calories.drop(columns=['User_ID','Calories'], axis=1)
Y = calories['Calories']

print(X)
print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

model = XGBRegressor()

model.fit(X_train, Y_train)

test_data_prediction = model.predict(X_test)

print(test_data_prediction)

mae = metrics.mean_absolute_error(Y_test, test_data_prediction)

print("Mean Absolute Error = ", mae)